/*
 * Copyright © 2026 James Carman
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jwcarman.who.core.spi;

import org.jwcarman.who.core.domain.ContactMethod;

/**
 * SPI for sending contact verification codes.
 * Required if trust-issuer-verification is false or when manual verification is needed.
 */
public interface ContactVerificationNotifier {

    /**
     * Send verification code to contact method.
     *
     * @param contact the contact method to verify
     * @param code the verification code (generated by Who)
     */
    void sendVerificationCode(ContactMethod contact, String code);
}
